# Generated by Django 4.0 on 2021-12-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nguoidung', '0007_auto_20211206_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomchat',
            name='RoomIDAPI',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='roomchat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='thongtinnguoidung',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tinnhan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
